### ISSUE TITLE
STL files seem unusable 

### ISSUE THREAD

**Issue by prgrobots** [ros-mobile-robots/remo_description#2]
The STL files wont open in CURA or windows 3D.

After downloading the repo, none of the STLs will open and the file sizes are different than what the github hosted version is?

Is the  the original Fusion 360 file somewhere so I can create the STLs myself?

When I clone with Github Desktop it gives me this error, it appears the  repository is over its data limit 

Cloning into 'C:\Users\PC\Documents\GitHub\remo_description'...
remote: Enumerating objects: 196, done.        
remote: Counting objects: 100% (196/196), done.        
remote: Compressing objects: 100% (134/134), done.        
remote: Total 196 (delta 81), reused 147 (delta 51), pack-reused 0        
Receiving objects: 100% (196/196), 44.62 KiB | 703.00 KiB/s, done.
Resolving deltas: 100% (81/81), done.
Downloading meshes/components/IMX219.stl (183 KB)
Error downloading object: meshes/components/IMX219.stl (1db7d12): Smudge error: Error downloading meshes/components/IMX219.stl (1db7d1227624a11c30d6b6da4815d4ca69a6699a2323c870b66d54be17c89912): batch response: **This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.**

Thanks

**Comment by prgrobots** [comment]
Thanks Franz,

Working now, looking forward to to getting started!

**Comment by fjp** [comment]
Your welcome and thanks for letting me know its working now. I hope the print works out fine but if you encounter any problems feel free to open a new issue :-)

**Comment by prgrobots** [comment]
Thanks Franz, its a lovely model

I have modified the Lidar deck to accommodate the A1M8-R6 ( https://www.dfrobot.com/product-1125.html ),  there are a few changes to make before its finished but you are welcome to add it to the repo.

**Comment by fjp** [comment]
Thank you @prgrobots.

Awesome, that would be a really useful addition. With it the overall robot becomes even more affordable for others to build. Once you are ready, feel free to open up a PR or you can also share the stl file in a new issue/discussion or reply here.

**Comment by prgrobots** [comment]
Hi Franz.

I have attached the alternate deck STL and some pictures of the build.  You will have to excuse my print,  I am using a 0.8mm nozzle for prototyping.

I also trimmed the camera mount (badly with tinkercad,  if only I had the original Fusion files) to print without supports for the Raspberry Pi camera and used a caster in place of the ball roller, I figure it will take the weight better 

![IMG20211115153845_00](https://user-images.githubusercontent.com/91106994/141779548-7d8cb940-1d03-4393-99ba-7bbac2637931.jpg)


![IMG20211115152143_00](https://user-images.githubusercontent.com/91106994/141779493-5f632e56-1112-48fd-9a72-4492be310f40.jpg)

![IMG20211115153903_00](https://user-images.githubusercontent.com/91106994/141779440-8d1f4931-d5cb-4f5a-b43e-d0ef2717955f.jpg)
![IMG20211115204000_00](https://user-images.githubusercontent.com/91106994/141783981-df01d8c3-a6f3-4293-ba58-b30efa9de15e.jpg)
![IMG20211115203912_00](https://user-images.githubusercontent.com/91106994/141784057-b5c117d3-7a3d-4bcf-9028-fbf0946f6738.jpg)
[STLs.zip](https://github.com/ros-mobile-robots/remo_description/files/7538730/STLs.zip)

**Comment by prgrobots** [comment]
I did want to ask about the Teensy. The encoders cant be going that fast, would a Seeed Studio Xiao or ESP32 work instead?

**Comment by fjp** [comment]
Really nice @prgrobots, this is a great design! Thanks a lot for sharing it :-)

In case you still need the Fusion files I can send them to you by mail, just contact me at ros@fjp.at

Either way, I would be happy to add your final STLs to the repository. Please let me know if you want to create a PR with the final files, or if I should add the ones you shared.

> I did want to ask about the Teensy. The encoders cant be going that fast, would a Seeed Studio Xiao or ESP32 work instead?

The quadrature encoders only give approximately 542 ticks. So these boards should work as well but I haven't tested it. However, would be interesting to know if they are also usable.
